USE [master]
GO
/****** Object:  Database [SPRING_SEC_HB]    Script Date: 20/10/2016 3:01:29 ******/
CREATE DATABASE [SPRING_SEC_HB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SPRING_SEC_HB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\SPRING_SEC_HB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SPRING_SEC_HB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\SPRING_SEC_HB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SPRING_SEC_HB] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SPRING_SEC_HB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SPRING_SEC_HB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [SPRING_SEC_HB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SPRING_SEC_HB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SPRING_SEC_HB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SPRING_SEC_HB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SPRING_SEC_HB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SPRING_SEC_HB] SET  MULTI_USER 
GO
ALTER DATABASE [SPRING_SEC_HB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SPRING_SEC_HB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SPRING_SEC_HB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SPRING_SEC_HB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [SPRING_SEC_HB]
GO
/****** Object:  Table [dbo].[APP_USER]    Script Date: 20/10/2016 3:01:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[APP_USER](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[sso_id] [varchar](30) NOT NULL,
	[password] [varchar](100) NOT NULL,
	[first_name] [varchar](30) NOT NULL,
	[last_name] [varchar](30) NOT NULL,
	[email] [varchar](30) NOT NULL,
	[state] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[sso_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[APP_USER_USER_PROFILE]    Script Date: 20/10/2016 3:01:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APP_USER_USER_PROFILE](
	[user_id] [bigint] NOT NULL,
	[user_profile_id] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[user_id] ASC,
	[user_profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[USER_PROFILE]    Script Date: 20/10/2016 3:01:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER_PROFILE](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[type] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[APP_USER_USER_PROFILE]  WITH CHECK ADD  CONSTRAINT [FK_APP_USER] FOREIGN KEY([user_id])
REFERENCES [dbo].[APP_USER] ([id])
GO
ALTER TABLE [dbo].[APP_USER_USER_PROFILE] CHECK CONSTRAINT [FK_APP_USER]
GO
ALTER TABLE [dbo].[APP_USER_USER_PROFILE]  WITH CHECK ADD  CONSTRAINT [FK_USER_PROFILE] FOREIGN KEY([user_profile_id])
REFERENCES [dbo].[USER_PROFILE] ([id])
GO
ALTER TABLE [dbo].[APP_USER_USER_PROFILE] CHECK CONSTRAINT [FK_USER_PROFILE]
GO
USE [master]
GO
ALTER DATABASE [SPRING_SEC_HB] SET  READ_WRITE 
GO
